<a href="https://colab.research.google.com/github/kurtlang123/CSST101-LAB/blob/main/Larioza_Labaratory_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Debate Arguments**

In [5]:
dabate <- data.frame(
  Argument_ID = c("A001", "A002", "A003", "A004", "A005", "A006"),
  Position = c("For", "For", "For", "Against", "Against", "Against"),
  Topic = c("Learning", "Productivity", "AI Literacy", "Academic Integrity", "Dependency", "Assessment"),
  Claim = c(
    "AI can provide students with immediate learning support.",
    "AI can help students complete routine academic tasks more efficiently.",
    "Allowing AI use can help students develop AI literacy.",
    "Undisclosed AI-generated work may create academic integrity concerns.",
    "Excessive AI use may reduce students' independent problem-solving practice.",
    "AI use may make it more difficult to determine whether submitted work reflects student learning."
  ))
dabate

  Argument_ID Position Topic
1 A001        For      Learning
2 A002        For      Productivity
3 A003        For      AI Literacy
4 A004        Against  Academic Integrity
5 A005        Against  Dependency
6 A006        Against  Assessment
  Claim
1 AI can provide students with immediate learning support.
2 AI can help students complete routine academic tasks more efficiently.
3 Allowing AI use can help students develop AI literacy.
4 Undisclosed AI-generated work may create academic integrity concerns.
5 Excessive AI use may reduce students' independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.

**2. Evidence**

In [2]:
df_evidence <- data.frame(
  Evidence_ID = c("E001", "E002", "E003", "E004", "E005", "E006"),
  Argument_ID = c("A001", "A002", "A003", "A004", "A005", "A006"),
  Evidence_Type = c("Research", "Research", "Policy", "Policy", "Research", "Research"),
  Strength = c("Strong", "Moderate", "Strong", "Strong", "Moderate", "Strong"),
  stringsAsFactors = FALSE
)
df_evidence

  Evidence_ID Argument_ID Evidence_Type Strength
1 E001        A001        Research      Strong
2 E002        A002        Research      Moderate
3 E003        A003        Policy        Strong
4 E004        A004        Policy        Strong
5 E005        A005        Research      Moderate
6 E006        A006        Research      Strong

**3. Table Arguments**

In [11]:
library(dplyr)

combined_arguments <- merge(dabate, df_evidence, by = "Argument_ID", all.x = TRUE)

combined_arguments

  Argument_ID Position Topic
1 A001        For      Learning
2 A002        For      Productivity
3 A003        For      AI Literacy
4 A004        Against  Academic Integrity
5 A005        Against  Dependency
6 A006        Against  Assessment
  Claim
1 AI can provide students with immediate learning support.
2 AI can help students complete routine academic tasks more efficiently.
3 Allowing AI use can help students develop AI literacy.
4 Undisclosed AI-generated work may create academic integrity concerns.
5 Excessive AI use may reduce students' independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.
  Evidence_ID Evidence_Type Strength
1 E001        Research      Strong
2 E002        Research      Moderate
3 E003        Policy        Strong
4 E004        Policy        Strong
5 E005        Research      Moderate
6 E006        Research      Strong

In [13]:
table(combined_arguments$Strength)

Moderate   Strong
       2        4

**4. Count Arguments**

In [7]:
library(dplyr)

argument_counts <- combined_arguments %>%
  group_by(Position) %>%
  summarise(Count = n())

argument_counts

  Position Count
1 Against  3
2 For      3

In [12]:
knowledge_base <- merge(
  combined_arguments,
  argument_counts,
  by = "Position",
  all.x = TRUE
)
print(knowledge_base)

  Position Argument_ID              Topic
1  Against        A004 Academic Integrity
2  Against        A005         Dependency
3  Against        A006         Assessment
4      For        A001           Learning
5      For        A002       Productivity
6      For        A003        AI Literacy
                                                                                             Claim
1                            Undisclosed AI-generated work may create academic integrity concerns.
2                      Excessive AI use may reduce students' independent problem-solving practice.
3 AI use may make it more difficult to determine whether submitted work reflects student learning.
4                                         AI can provide students with immediate learning support.
5                           AI can help students complete routine academic tasks more efficiently.
6                                           Allowing AI use can help students develop AI literacy.
  Evidence_ID Evidence_Type Strength Count
1        E004        Policy   Strong     3
2        E005      Research Moderate     3
3        E006      Research   Strong     3
4        E001      Research   Strong     3
5        E002      Research Moderate     3
6        E003        Policy   Strong     3

**Convert Evidence Strength into a score**

In [14]:
get_score <- function(strength){

  if (strength == "Strong"){
    return(3)
  } else if(strength == "Moderate"){
    return(2)
  } else if(strength == "Weak"){
    return(1)
  } else {
    return(0)
  }

}

get_score("Moderate")

[1] 2

**Add Evidence Scores.**

In [15]:
knowledge_base$Evidence_Score <- sapply(
  knowledge_base$Strength,
  get_score
)

print(knowledge_base)

  Position Argument_ID              Topic
1  Against        A004 Academic Integrity
2  Against        A005         Dependency
3  Against        A006         Assessment
4      For        A001           Learning
5      For        A002       Productivity
6      For        A003        AI Literacy
                                                                                             Claim
1                            Undisclosed AI-generated work may create academic integrity concerns.
2                      Excessive AI use may reduce students' independent problem-solving practice.
3 AI use may make it more difficult to determine whether submitted work reflects student learning.
4                                         AI can provide students with immediate learning support.
5                           AI can help students complete routine academic tasks more efficiently.
6                                           Allowing AI use can help students develop AI literacy.
  Evidence_ID Evidence_Type Strength Count Evidence_Score
1        E004        Policy   Strong     3              3
2        E005      Research Moderate     3              2
3        E006      Research   Strong     3              3
4        E001      Research   Strong     3              3
5        E002      Research Moderate     3              2
6        E003        Policy   Strong     3              3

**Convert Evidence Score to Support**

In [16]:
classify_support <- function(score){

  if (score == 3){
    return("Strongly Supported")
  } else if(score == 2){
    return("Moderately Supported")
  } else if(score == 1){
    return("Weakly Supported")
  } else {
    return("No Support")
  }

}
classify_support(3)

[1] "Strongly Supported"

**Add Evidence to Support**

In [17]:
knowledge_base$Support_Level <- sapply(
  knowledge_base$Evidence_Score,
  classify_support
)

print(knowledge_base)

  Position Argument_ID              Topic
1  Against        A004 Academic Integrity
2  Against        A005         Dependency
3  Against        A006         Assessment
4      For        A001           Learning
5      For        A002       Productivity
6      For        A003        AI Literacy
                                                                                             Claim
1                            Undisclosed AI-generated work may create academic integrity concerns.
2                      Excessive AI use may reduce students' independent problem-solving practice.
3 AI use may make it more difficult to determine whether submitted work reflects student learning.
4                                         AI can provide students with immediate learning support.
5                           AI can help students complete routine academic tasks more efficiently.
6                                           Allowing AI use can help students develop AI literacy.
  Evidence_ID Evidence_Type Strength Count Evidence_Score        Support_Level
1        E004        Policy   Strong     3              3   Strongly Supported
2        E005      Research Moderate     3              2 Moderately Supported
3        E006      Research   Strong     3              3   Strongly Supported
4        E001      Research   Strong     3              3   Strongly Supported
5        E002      Research Moderate     3              2 Moderately Supported
6        E003        Policy   Strong     3              3   Strongly Supported

In [20]:
search_topic <- function(topic){
  result <- subset(
  knowledge_base,
  Topic == topic
)
if(nrow(result) ==0){
  cat("topic not found")
}else{
  print(result)
}
}
search_topic("Learning")

  Position Argument_ID    Topic
4      For        A001 Learning
                                                     Claim Evidence_ID
4 AI can provide students with immediate learning support.        E001
  Evidence_Type Strength Count Evidence_Score      Support_Level
4      Research   Strong     3              3 Strongly Supported